dromo_admin_local:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
    
#dromo_api_promociones:
#    resource: "@DromoApiPromocionesBundle/Resources/config/routing.yml"
#    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#REST 
rest : 
  type : rest 
  resource : "routing_rest.yml"
  prefix : /api
 
#SEGURITY
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
