premio:
    path:     /
    defaults: { _controller: "AppBundle:Premio:index" }

premio_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Premio:show" }

premio_new:
    path:     /new
    defaults: { _controller: "AppBundle:Premio:new" }

premio_create:
    path:     /create
    defaults: { _controller: "AppBundle:Premio:create" }
    methods:  POST

premio_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Premio:edit" }

premio_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Premio:update" }
    methods:  [POST, PUT]

premio_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Premio:delete" }
    methods:  [POST, DELETE]
