visitalc:
    path:     /
    defaults: { _controller: "AppBundle:VisitaLocalComercial:index" }

visitalc_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:VisitaLocalComercial:show" }

visitalc_new:
    path:     /new
    defaults: { _controller: "AppBundle:VisitaLocalComercial:new" }

visitalc_create:
    path:     /create
    defaults: { _controller: "AppBundle:VisitaLocalComercial:create" }
    methods:  POST

visitalc_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:VisitaLocalComercial:edit" }

visitalc_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:VisitaLocalComercial:update" }
    methods:  [POST, PUT]

visitalc_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:VisitaLocalComercial:delete" }
    methods:  [POST, DELETE]
    
visitalc_ajax_grafico:
    path:     /ajax_grafico
    defaults: { _controller: "AppBundle:VisitaLocalComercial:ajax" }
    condition: "request.isXmlHttpRequest()"
