app_comentario:
    resource: "@AppBundle/Resources/config/routing/comentario.yml"
    prefix:   local/comentario

app_comentarios:
    resource: "@AppBundle/Resources/config/routing/comentarios.yml"
    prefix:   admin/comentarios

app_sucursal:
    resource: "@AppBundle/Resources/config/routing/sucursal.yml"
    prefix:   admin/sucursal
    
app_direccion:
    resource: "@AppBundle/Resources/config/routing/direccion.yml"
    prefix:   admin/direccion

app_sucursales:
    resource: "@AppBundle/Resources/config/routing/sucursales.yml"
    prefix:   local/sucursales

app_localcomercial:
    resource: "@AppBundle/Resources/config/routing/localcomercial.yml"
    prefix:   admin/localcomercial

app_programacionPremio:
    resource: "@AppBundle/Resources/config/routing/programacionPremio.yml"
    prefix:   admin/programacionPremio

app_premios:
    resource: "@AppBundle/Resources/config/routing/premios.yml"
    prefix:   admin/premios
    
app_premio:
    resource: "@AppBundle/Resources/config/routing/premio.yml"
    prefix:   local/premio

app_index_local:
    path:     /
    defaults: { _controller: "AppBundle:Default:index" }
    
app_promocion:
    resource: "@AppBundle/Resources/config/routing/promocion.yml"
    prefix:   local/promocion

app_programacion:
    resource: "@AppBundle/Resources/config/routing/programacion.yml"
    prefix:   local/programacion
    
app_validar_cupon:
    resource: "@AppBundle/Resources/config/routing/cupon.yml"
    prefix: local/cupon



